/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomSnackbar: typeof import('./src/components/CustomSnackbar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RocketEmptyState: typeof import('./src/components/RocketEmptyState.vue')['default']
    RocketErrorState: typeof import('./src/components/RocketErrorState.vue')['default']
    RocketItemList: typeof import('./src/components/RocketItemList.vue')['default']
    RocketSearchBar: typeof import('./src/components/RocketSearchBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
